storage:
  type: nfs  # Options: 'nfs' or 'configmap'

nfs:
  server: 192.168.5.5
  path: /volume1/docker/homepage

configMap:
  name: homepage-configmap

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: dashy.k.jpcortesp.place
  path: /
  tlsprovider: letsencrypt-godaddy

gateway:
  enabled: false
  hostname: "*.k.jpcortesp.place"         # Wildcard cert listener
  routeHost: "homepage.k.jpcortesp.place"   # Homepage's actual subdomain
  tlsSecret: wildcard-k-jpcortesp-place-tls
