apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "uptime-kuma.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "uptime-kuma.name" . }}
    spec:
      securityContext:
        fsGroup: 1000  # 👈 This gives group ownership over mounted volume

    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc