{{- if .Values.url }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "uptime-kuma.fullname" . }}
                port:
                  number: 3001
  tls:
    - hosts:
        - {{ .Values.url }}
      secretName: uptime-kuma-tls
{{- end }}