{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: web
      port: {{ $app.webPort | default $app.port }}
      targetPort: {{ $app.webPort | default $app.port }}
    {{- if eq $name "qbittorrent" }}
    - name: bt-tcp
      port: {{ $app.peerPort }}
      targetPort: {{ $app.peerPort }}
    - name: bt-udp
      port: {{ $app.peerPort }}
      targetPort: {{ $app.peerPort }}
      protocol: UDP
    {{- end }}
---
{{- end }}
{{- end }}
