storage:
  type: nfs  # Options: 'nfs' or 'configmap'

nfs:
  server: 192.168.5.5
  path: /volume1/docker/dashy

configMap:
  name: dashy-configmap

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: dashy.k.jpcortesp.place
  path: /
  tls: true
