{{- range $name, $app := .Values.apps }}
{{- if and $app.enabled $app.ingressHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ $app.ingressHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $app.webPort | default $app.port }}
---
{{- end }}
{{- end }}
