{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dashy-route
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: dashy-gateway
  hostnames:
    - "{{ .Values.gateway.routeHost }}"
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}
          port: {{ .Values.service.port }}
{{- end }}