apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "*" # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
      volumes:
        {{- if eq .Values.storage.type "nfs" }}
        - name: homepage-config
          persistentVolumeClaim:
            claimName: homepage-nfs-pvc
        {{- else if eq .Values.storage.type "configmap" }}
        - name: homepage-config
          configMap:
            name: {{ .Values.configMap.name }}
        {{- end }}
