name: Deploy Helm Charts via GitHub Pages

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/deploy-charts.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repo
        uses: actions/checkout@v3

      - name: 🧰 Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: 🧩 Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: 🧠 Identify Changed Charts
        id: changed
        run: |
          echo "CHANGED_DIRS<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^charts/' | cut -d/ -f2 | sort -u >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 🔼 Bump Chart Versions & Package
        run: |
          TODAY=$(date +%F)
          mkdir -p public
          echo "${{ steps.changed.outputs.CHANGED_DIRS }}" | while read chart; do
            chart_path="charts/$chart/Chart.yaml"
            if [ -f "$chart_path" ]; then
              current_version=$(yq '.version' "$chart_path")
              base_version="${current_version%.*}"
              patch="${current_version##*.}"
              next_patch=$((patch + 1))
              new_version="${base_version}.${next_patch}"
              echo "📦 $chart: version $current_version → $new_version, appVersion → $TODAY"
              yq eval ".version = \"$new_version\" | .appVersion = \"$TODAY\"" -i "$chart_path"
              helm package "charts/$chart" --destination public
            fi
          done

          helm repo index public --url https://jpcortesp.github.io/jp-helm-repos

      - name: 🚫 Add .nojekyll
        run: touch public/.nojekyll

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true