name: Deploy Helm Charts via GitHub Pages

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/deploy-charts.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repo
        uses: actions/checkout@v3

      - name: 🧰 Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: 📦 Package Helm Charts
        run: |
          rm -rf public
          mkdir -p public
          cd charts
          helm package dashy
          helm package media-stack
          mv *.tgz ../public/
          cd ..
          helm repo index public --url https://jpcortesp.github.io/jp-helm-repos

      - name: 🚫 Add .nojekyll
        run: touch public/.nojekyll

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
