name: Deploy Helm Charts

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout full history so we can access gh-pages
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # ✅ Set up Helm CLI
      - name: Set up Helm
        uses: azure/setup-helm@v3

      # ✅ Pull existing index.yaml from gh-pages
      - name: Clone gh-pages branch
        run: |
          git fetch origin gh-pages
          git worktree add gh-pages origin/gh-pages

      # ✅ Package charts
      - name: Package charts
        run: |
          mkdir -p packaged
          helm package charts/* --destination packaged
          ls -la packaged

      # ✅ Merge with existing index.yaml
      - name: Generate Helm repo index
        run: |
          helm repo index packaged \
            --url https://jpchart.jpcortesp.dev \
            --merge gh-pages/index.yaml

      # ✅ Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packaged
          publish_branch: gh-pages
