name: Deploy Helm Charts via GitHub Pages

on:
  push:
    paths:
      - 'charts/**'
      - '.github/workflows/deploy-charts.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repo
        uses: actions/checkout@v3

      - name: 🧰 Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0
          
      - name: 🧩 Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: 🕓 Set Date-Based appVersion & Package Charts
        run: |
          rm -rf public
          mkdir -p public
          TODAY=$(date +%F)  # Format: YYYY-MM-DD

          for dir in charts/*/; do
            chart_file="${dir}Chart.yaml"
            if [ -f "$chart_file" ]; then
              echo "Updating appVersion in $chart_file to $TODAY"
              # Use yq to update appVersion in-place
              yq eval ".appVersion = \"$TODAY\"" -i "$chart_file"
              helm package "$dir" --destination public
            fi
          done

          helm repo index public --url https://jpcortesp.github.io/jp-helm-repos

      - name: 🚫 Add .nojekyll
        run: touch public/.nojekyll

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
